-- Core Work Order schema. This migration must run before migrations that extend
-- work_orders or create tables with foreign keys to it.

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'user',
    division TEXT,
    pic_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.work_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    brand TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Design', 'Programming', 'Asset')),
    description TEXT NOT NULL,
    platform TEXT,
    dimension TEXT,
    deadline DATE NOT NULL,
    priority TEXT NOT NULL DEFAULT 'P2' CHECK (priority IN ('P1', 'P2', 'P3')),
    urgent_reason TEXT,
    status TEXT NOT NULL DEFAULT 'Open',
    admin_notes TEXT,
    assigned_to UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_role TEXT,
    final_asset_url TEXT,
    meeting_type TEXT CHECK (meeting_type IN ('Online', 'Offline')),
    meeting_date TIMESTAMPTZ,
    meeting_link TEXT,
    meeting_location TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_work_orders_user_id ON public.work_orders(user_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_status ON public.work_orders(status);
CREATE INDEX IF NOT EXISTS idx_work_orders_assigned_to ON public.work_orders(assigned_to);
CREATE INDEX IF NOT EXISTS idx_work_orders_created_at ON public.work_orders(created_at DESC);

CREATE TABLE IF NOT EXISTS public.work_order_attachments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wo_id UUID NOT NULL REFERENCES public.work_orders(id) ON DELETE CASCADE,
    file_url TEXT NOT NULL,
    file_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_work_order_attachments_wo_id
    ON public.work_order_attachments(wo_id);

ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_attachments ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.work_orders TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.work_order_attachments TO authenticated;

DROP POLICY IF EXISTS "Users can create their own work orders" ON public.work_orders;
CREATE POLICY "Users can create their own work orders"
    ON public.work_orders FOR INSERT TO authenticated
    WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can view their own work orders" ON public.work_orders;
CREATE POLICY "Users can view their own work orders"
    ON public.work_orders FOR SELECT TO authenticated
    USING (
        user_id = auth.uid()
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('head_it', 'designer', 'it_dev', 'it_support')
        )
    );

DROP POLICY IF EXISTS "Staff can update work orders" ON public.work_orders;
CREATE POLICY "Staff can update work orders"
    ON public.work_orders FOR UPDATE TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('head_it', 'designer', 'it_dev', 'it_support')
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('head_it', 'designer', 'it_dev', 'it_support')
        )
    );

DROP POLICY IF EXISTS "Users can view attachments for visible work orders" ON public.work_order_attachments;
CREATE POLICY "Users can view attachments for visible work orders"
    ON public.work_order_attachments FOR SELECT TO authenticated
    USING (EXISTS (SELECT 1 FROM public.work_orders wo WHERE wo.id = wo_id));

DROP POLICY IF EXISTS "Users can attach files to their own work orders" ON public.work_order_attachments;
CREATE POLICY "Users can attach files to their own work orders"
    ON public.work_order_attachments FOR INSERT TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.work_orders wo
            WHERE wo.id = wo_id AND wo.user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Users can delete attachments from their own work orders" ON public.work_order_attachments;
CREATE POLICY "Users can delete attachments from their own work orders"
    ON public.work_order_attachments FOR DELETE TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.work_orders wo
            WHERE wo.id = wo_id AND wo.user_id = auth.uid()
        )
    );

INSERT INTO storage.buckets (id, name, public)
VALUES ('attachments', 'attachments', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

DROP POLICY IF EXISTS "Authenticated users can upload work order files" ON storage.objects;
CREATE POLICY "Authenticated users can upload work order files"
    ON storage.objects FOR INSERT TO authenticated
    WITH CHECK (
        bucket_id = 'attachments'
        AND (storage.foldername(name))[1] = auth.uid()::TEXT
    );

DROP POLICY IF EXISTS "Public can read work order files" ON storage.objects;
CREATE POLICY "Public can read work order files"
    ON storage.objects FOR SELECT TO public
    USING (bucket_id = 'attachments');

-- PostgREST normally reloads automatically after DDL; this makes the migration
-- deterministic for projects where its schema cache was previously stale.
NOTIFY pgrst, 'reload schema';
